# Generated by Django 5.2.9 on 2025-12-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя художника')),
                ('birth_year', models.IntegerField(verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('country', models.CharField(default='Великобритания', max_length=50, verbose_name='Страна')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название картины')),
                ('year', models.IntegerField(verbose_name='Год создания')),
                ('technique', models.CharField(default='Масло, холст', max_length=100, verbose_name='Техника')),
                ('dimensions', models.CharField(help_text='например: 100×150 см', max_length=50, verbose_name='Размеры')),
                ('location', models.CharField(default='Галерея Тейт, Лондон', max_length=100, verbose_name='Местонахождение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artist', verbose_name='Художник')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
            },
        ),
    ]
