# Generated by Django 5.2.9 on 2025-12-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(default='Великобритания', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя художника'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=models.CharField(default='Галерея Тейт, Лондон', max_length=200, verbose_name='Местонахождение'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.CharField(max_length=50, verbose_name='Год создания'),
        ),
    ]
